### ISSUE TITLE
nav

### ISSUE THREAD

**Issue by jolylai** [jolylai/awesome-css#4]
# 超出隐藏
超出隐藏只在display 为 block 和 inline-block 才能生效
```css
a {
    overflow: hidden;
    display: inline-block;
}
```
